"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

import { Button, Icon, IconButton } from "@zmzai/theme";

type Workspace = { id: string; name: string };
type Automation = { automationId: string; workspaceId: string; name: string; goal: string; schedule: string; status: "active" | "paused"; lastRunAt: string | null };

async function json<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, cache: "no-store" }); const body = await response.json().catch(() => null) as { error?: string } | T | null; if (!response.ok) throw new Error(body && typeof body === "object" && body !== null && "error" in body ? String(body.error) : "请求失败"); return body as T; }

export default function AutomationsPage() {
  const router = useRouter();
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [items, setItems] = useState<Automation[]>([]); const [workspaceId, setWorkspaceId] = useState(""); const [name, setName] = useState(""); const [goal, setGoal] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const fetchPage = () => Promise.all([json<{ workspaces: Workspace[] }>("/api/workspaces"), json<{ automations: Automation[] }>("/api/automations")]);
  const load = async () => { const [ws, automations] = await fetchPage(); setWorkspaces(ws.workspaces); setWorkspaceId((current) => current || ws.workspaces[0]?.id || ""); setItems(automations.automations); };
  useEffect(() => { let cancelled = false; void fetchPage().then(([ws, automations]) => { if (cancelled) return; setWorkspaces(ws.workspaces); setWorkspaceId((current) => current || ws.workspaces[0]?.id || ""); setItems(automations.automations); }).catch((cause: unknown) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "无法加载自动化"); }); return () => { cancelled = true; }; }, []);
  const create = async () => { if (!name.trim() || !goal.trim() || !workspaceId) return; setBusy("create"); try { await json("/api/automations", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ workspaceId, name, goal }) }); setName(""); setGoal(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "创建失败"); } finally { setBusy(null); } };
  const run = async (id: string) => { setBusy(id); try { const result = await json<{ session: { id: string } }>(`/api/automations/${id}/run`, { method: "POST", headers: { "idempotency-key": crypto.randomUUID() } }); router.push(`/fw/s/${result.session.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "启动失败"); setBusy(null); } };
  const toggle = async (item: Automation) => { setBusy(item.automationId); try { await json(`/api/automations/${item.automationId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: item.status === "active" ? "paused" : "active" }) }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "更新失败"); } finally { setBusy(null); } };
  return <main className="product-page"><header className="product-page-head"><div><Link href="/fw" className="product-back"><Icon name="arrow-left" size={14} />返回工作台</Link><span className="eyebrow">重复工作</span><h1>自动化</h1><p>把成功的任务保存成可手动触发的模板。</p></div><Link href="/fw" className="product-action-link">新对话 <Icon name="arrow-up-right" size={14} /></Link></header>{error && <div className="product-error">{error}</div>}<section className="automation-create"><select value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)} aria-label="选择 Workspace">{workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select><input value={name} onChange={(event) => setName(event.target.value)} placeholder="自动化名称" /><input value={goal} onChange={(event) => setGoal(event.target.value)} placeholder="每次运行要完成什么" /><Button type="button" onClick={() => void create()} disabled={busy === "create" || !name.trim() || !goal.trim()}><Icon name="plus" size={14} />保存模板</Button></section><section className="automation-list">{items.length ? items.map((item) => <article className="automation-row" key={item.automationId}><div className="automation-copy"><div className="automation-title"><span className={`automation-status ${item.status}`} /> <h2>{item.name}</h2></div><p>{item.goal}</p><small>{item.schedule}{item.lastRunAt ? ` · 上次运行 ${new Date(item.lastRunAt).toLocaleString("zh-CN")}` : ""}</small></div><div className="automation-actions"><Button type="button" variant="secondary" size="sm" disabled={busy === item.automationId || item.status === "paused"} onClick={() => void run(item.automationId)}><Icon name="play" size={13} />运行</Button><IconButton size="sm" label={item.status === "active" ? "暂停" : "恢复"} onClick={() => void toggle(item)}><Icon name={item.status === "active" ? "pause" : "play"} size={13} /></IconButton></div></article>) : <div className="product-empty"><Icon name="clock" size={22} /><strong>还没有自动化</strong><p>先完成一次任务，再把它保存为模板。</p></div>}</section></main>;
}
