"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import { Button, Icon, IconButton } from "@zmzai/theme";

type Workspace = { id: string; name: string };
type Connector = { id: string; name: string; transport: string; url: string; status: "untested" | "ready" | "error"; enabled: boolean; lastError: string | null };
async function json<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, cache: "no-store" }); const body = await response.json().catch(() => null) as { error?: string } | T | null; if (!response.ok) throw new Error(body && typeof body === "object" && body !== null && "error" in body ? String(body.error) : "请求失败"); return body as T; }

export default function ConnectorsPage() {
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]); const [workspaceId, setWorkspaceId] = useState(""); const [items, setItems] = useState<Connector[]>([]); const [name, setName] = useState(""); const [url, setUrl] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const fetchPage = async (id?: string) => { const ws = await json<{ workspaces: Workspace[] }>("/api/workspaces"); const selected = id || workspaceId || ws.workspaces[0]?.id || ""; const connectors = selected ? (await json<{ connectors: Connector[] }>(`/api/workspaces/${selected}/connectors`)).connectors : []; return { workspaces: ws.workspaces, selected, connectors }; };
  const load = async (id?: string) => { const result = await fetchPage(id); setWorkspaces(result.workspaces); setWorkspaceId(result.selected); setItems(result.connectors); };
  // Load the initial workspace once; workspace selection uses the explicit id path below.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { let cancelled = false; void fetchPage().then((result) => { if (cancelled) return; setWorkspaces(result.workspaces); setWorkspaceId(result.selected); setItems(result.connectors); }).catch((cause: unknown) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "无法加载连接器"); }); return () => { cancelled = true; }; }, []);
  const selectWorkspace = (id: string) => { setWorkspaceId(id); void load(id).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "无法加载连接器")); };
  const create = async () => { if (!workspaceId || !name.trim() || !url.trim()) return; setBusy("create"); try { await json(`/api/workspaces/${workspaceId}/connectors`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, url, transport: "streamable-http", headers: {} }) }); setName(""); setUrl(""); await load(workspaceId); } catch (cause) { setError(cause instanceof Error ? cause.message : "创建失败"); } finally { setBusy(null); } };
  const test = async (id: string) => { setBusy(id); try { await json(`/api/workspaces/${workspaceId}/connectors/${id}/test`, { method: "POST" }); await load(workspaceId); } catch (cause) { setError(cause instanceof Error ? cause.message : "连接测试失败"); } finally { setBusy(null); } };
  const toggle = async (item: Connector) => { setBusy(item.id); try { const connectorIds = items.filter((candidate) => candidate.enabled !== (candidate.id === item.id)).map((candidate) => candidate.id); await json(`/api/workspaces/${workspaceId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ connectorIds }) }); await load(workspaceId); } catch (cause) { setError(cause instanceof Error ? cause.message : "更新失败"); } finally { setBusy(null); } };
  return <main className="product-page"><header className="product-page-head"><div><Link href="/fw" className="product-back"><Icon name="arrow-left" size={14} />返回工作台</Link><span className="eyebrow">外部能力</span><h1>连接器</h1><p>管理 Agent 可以访问的 MCP 服务和授权范围。</p></div><Link href="/fw" className="product-action-link">新对话 <Icon name="arrow-up-right" size={14} /></Link></header>{error && <div className="product-error">{error}</div>}<section className="connector-toolbar"><select value={workspaceId} onChange={(event) => selectWorkspace(event.target.value)} aria-label="选择 Workspace">{workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select><input value={name} onChange={(event) => setName(event.target.value)} placeholder="连接器名称" /><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com/mcp" /><Button type="button" onClick={() => void create()} disabled={busy === "create" || !name.trim() || !url.trim()}><Icon name="plus" size={14} />添加连接器</Button></section><section className="connector-list">{items.length ? items.map((item) => <article className="connector-row" key={item.id}><div className="connector-copy"><div className="connector-title"><span className={`connector-status-dot ${item.status}`} /><h2>{item.name}</h2><small>{item.transport}</small>{!item.enabled && <small>已停用</small>}</div><p>{item.url}</p>{item.lastError && <em>{item.lastError}</em>}</div><div className="connector-actions"><Button type="button" variant="secondary" size="sm" disabled={busy === item.id} onClick={() => void test(item.id)}><Icon name="refresh" size={13} />测试连接</Button><IconButton size="sm" label={item.enabled ? "停用连接器" : "启用连接器"} disabled={busy === item.id} onClick={() => void toggle(item)}><Icon name={item.enabled ? "pause" : "play"} size={13} /></IconButton></div></article>) : <div className="product-empty"><Icon name="link" size={22} /><strong>还没有连接器</strong><p>添加一个公开 HTTPS MCP 地址。</p></div>}</section></main>;
}
